# Generated by Django 3.1.6 on 2021-02-20 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tipoDocumento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, unique=True)),
                ('siglas', models.CharField(max_length=10)),
                ('expedicion', models.DateField()),
                ('alertiy', models.BooleanField(default=True)),
                ('alert6m', models.BooleanField(default=True)),
                ('alert3m', models.BooleanField(default=True)),
                ('alerti1m', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'tipoDocumentos',
            },
        ),
    ]
